### PR TITLE
Remove allow_root mount option

### LINKED ISSUE #339: mount.go: undefined: fuse.AllowRoot ???
Trying to compile on debian 9.9

I installed golang
`go version go1.13.6 linux/amd64`

I ran go get -u github.com/dweidenfeld/plexdrive
Which outputs
```
# github.com/dweidenfeld/plexdrive/mount
gocode/src/github.com/dweidenfeld/plexdrive/mount/mount.go:52:30: undefined: fuse.AllowRoot

```
I have no idea what is wrong. I haven't been able to find anything relevant searching the web.

### PR DESCRIPTION
**Pull request by felixbuenemann**
This is no longer supported, because fuse.AllowRoot() was removed in https://github.com/bazil/fuse/commit/e0b89709bc6481f1345b6e19363cf18766e53fc7.

Fixes #339

### CODE REVIEW

**Comment by felixbuenemann** [comment]
Looks like bazil.org/fuse master also broke support for go < 1.13:

> bazil.org/fuse/fuse.go:410:5: undefined: errors.As

**Comment by felixbuenemann** [comment]
I opened https://github.com/bazil/fuse/issues/236 to clarify backwards compatibility.

Depending on how it goes we might consider vendoring an older version of the fuse package.

**Comment by felixbuenemann** [comment]
@dweidenfeld What's you position on this? – Should we drop support for golang < 1.13 or vendor the fuse package?

**Comment by Nothing4You** [comment]
fwiw debian stable ships with 1.11. removing support for older versions means debian stable users building this themselves must download a newer golang version (which admittedly isn't too hard).

**Comment by Nothing4You** [comment]
to add to that, debian oldstable ships 1.7, oldstable-backports 1.11, stable-backports 1.13.

**Comment by felixbuenemann** [comment]
Yeah, current Ubuntu LTS 18.04 ships with 1.10, but you can add a PPA for newer versions.

**Comment by felixbuenemann** [comment]
I've pushed an alternate solution using Go Modules to lock down dependencies in #341.

Unfortunately that also drops Go < 1.11.4 from the supported versions, since that is the minimum version with the required Go Modules support.

Potentially Plexdrive can still be built on older Go versions, if the dependencies are properly downgraded using "go get", but I have no intention of supporting such hacks in CI or introducing a third party dependency management tool.

**Comment by dweidenfeld** [comment]
I'd recommend sticking to the newest versions. Especially version 1.14 will be an interesting release since it shall be 30x faster in using the defer statement. This is a functionality mainly used in the cache so I think the performance of plexdrive will be much better with the newest go versions ;)

**Comment by felixbuenemann** [comment]
@dweidenfeld Just because we support older Go versions doesn't mean we can't support new Go versions.

I think it makes sense to support older Go versions that are still widely used, at least if we don't have regular releases.

If there are regular releases it doesn't really matter, since people can just download the right binaries for their system.

Do you know if it is possible and would you be OK with if contributors like me to publish new releases?

**Comment by dweidenfeld** [comment]
Sure. Feel free to publish new releases!

**Comment by felixbuenemann** [comment]
@dweidenfeld I bumped Travis to Go 1.13+ to make the build happy. Do you mind reviewing so I can merge the fix? (I can't review my own PRs)
