### ISSUE TITLE
mount.go: undefined: fuse.AllowRoot ???

### ISSUE THREAD

**Issue by bjstrange** [dweidenfeld/plexdrive#339]
Trying to compile on debian 9.9

I installed golang
`go version go1.13.6 linux/amd64`

I ran go get -u github.com/dweidenfeld/plexdrive
Which outputs
```
# github.com/dweidenfeld/plexdrive/mount
gocode/src/github.com/dweidenfeld/plexdrive/mount/mount.go:52:30: undefined: fuse.AllowRoot

```
I have no idea what is wrong. I haven't been able to find anything relevant searching the web.

**Comment by felixbuenemann** [comment]
Looks like it is caused by an update to bazil.org/fuse:

https://github.com/bazil/fuse/commit/e0b89709bc6481f1345b6e19363cf18766e53fc7

I'll look into it.

**Comment by potpot59** [comment]
Can't compile too.
Waiting for #340 or #341 🙃
